import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const templates = [
  // Social Media Templates
  {
    name: 'Instagram Post - Bold Typography',
    description: 'Modern Instagram post template with bold text and vibrant colors',
    category: 'social-media',
    widthPx: 1080,
    heightPx: 1080,
    tags: ['instagram', 'social', 'modern', 'bold'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1080,
          height: 1080,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'rect',
          left: 100,
          top: 100,
          width: 880,
          height: 300,
          fill: '#FFFFFF',
          rx: 20,
          ry: 20,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 150,
          top: 180,
          width: 780,
          fontSize: 72,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#2B5FD9',
          text: 'YOUR TITLE HERE',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 150,
          top: 550,
          width: 780,
          fontSize: 36,
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'Add your message or call to action',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Instagram Post - Minimal Quote',
    description: 'Clean and minimal quote template for Instagram',
    category: 'social-media',
    widthPx: 1080,
    heightPx: 1080,
    tags: ['instagram', 'quote', 'minimal', 'clean'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1080,
          height: 1080,
          fill: '#F8F9FA',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 140,
          top: 350,
          width: 800,
          fontSize: 56,
          fontFamily: 'Inter',
          fontStyle: 'italic',
          fill: '#1A1A1A',
          text: '"Your inspiring quote goes here"',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'rect',
          left: 440,
          top: 550,
          width: 200,
          height: 4,
          fill: '#E63946',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 340,
          top: 580,
          width: 400,
          fontSize: 28,
          fontFamily: 'Inter',
          fill: '#666666',
          text: '— Author Name',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Facebook Post - Product Showcase',
    description: 'Eye-catching product showcase for Facebook',
    category: 'social-media',
    widthPx: 1200,
    heightPx: 630,
    tags: ['facebook', 'product', 'showcase'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 600,
          height: 630,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'rect',
          left: 600,
          top: 0,
          width: 600,
          height: 630,
          fill: '#FFFFFF',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 650,
          top: 150,
          width: 500,
          fontSize: 54,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#1A1A1A',
          text: 'NEW PRODUCT',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 650,
          top: 240,
          width: 500,
          fontSize: 32,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'Discover our latest innovation',
          selectable: true,
        },
        {
          type: 'rect',
          left: 650,
          top: 380,
          width: 200,
          height: 60,
          fill: '#E63946',
          rx: 8,
          ry: 8,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 680,
          top: 395,
          width: 140,
          fontSize: 24,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'SHOP NOW',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Twitter Header - Personal Brand',
    description: 'Professional Twitter header for personal branding',
    category: 'social-media',
    widthPx: 1500,
    heightPx: 500,
    tags: ['twitter', 'header', 'personal'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1500,
          height: 500,
          fill: 'linear-gradient(135deg, #2B5FD9 0%, #1E3A8A 100%)',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 100,
          top: 150,
          width: 700,
          fontSize: 72,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'YOUR NAME',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 100,
          top: 250,
          width: 700,
          fontSize: 36,
          fontFamily: 'Inter',
          fill: '#E0E7FF',
          text: 'Your tagline or expertise',
          selectable: true,
        },
      ],
    },
  },

  // Banner Templates
  {
    name: 'Web Banner - Announcement',
    description: 'Eye-catching banner for website announcements',
    category: 'banner',
    widthPx: 1200,
    heightPx: 300,
    tags: ['web', 'banner', 'announcement'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1200,
          height: 300,
          fill: '#1A1A1A',
          selectable: true,
        },
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 10,
          height: 300,
          fill: '#E63946',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 50,
          top: 80,
          width: 700,
          fontSize: 56,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'BIG ANNOUNCEMENT',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 50,
          top: 160,
          width: 700,
          fontSize: 28,
          fontFamily: 'Inter',
          fill: '#CCCCCC',
          text: 'Something exciting is coming soon',
          selectable: true,
        },
        {
          type: 'rect',
          left: 900,
          top: 100,
          width: 250,
          height: 100,
          fill: '#2B5FD9',
          rx: 12,
          ry: 12,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 930,
          top: 130,
          width: 190,
          fontSize: 32,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'LEARN MORE',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'YouTube Thumbnail - Tutorial',
    description: 'Attention-grabbing YouTube thumbnail for tutorials',
    category: 'banner',
    widthPx: 1280,
    heightPx: 720,
    tags: ['youtube', 'thumbnail', 'tutorial'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1280,
          height: 720,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'rect',
          left: 40,
          top: 40,
          width: 1200,
          height: 640,
          fill: 'transparent',
          stroke: '#FFFFFF',
          strokeWidth: 8,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 100,
          top: 200,
          width: 1080,
          fontSize: 96,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'HOW TO',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 100,
          top: 350,
          width: 1080,
          fontSize: 64,
          fontFamily: 'Inter',
          fill: '#FFEB3B',
          text: 'Your Tutorial Topic',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'rect',
          left: 480,
          top: 500,
          width: 320,
          height: 120,
          fill: '#E63946',
          rx: 60,
          ry: 60,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 520,
          top: 530,
          width: 240,
          fontSize: 48,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'WATCH',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },

  // Business Card Templates
  {
    name: 'Business Card - Modern Professional',
    description: 'Clean and modern business card design',
    category: 'business-card',
    widthPx: 1050,
    heightPx: 600,
    tags: ['business', 'professional', 'modern'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1050,
          height: 600,
          fill: '#FFFFFF',
          selectable: true,
        },
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 400,
          height: 600,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 450,
          top: 150,
          width: 550,
          fontSize: 48,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#1A1A1A',
          text: 'John Doe',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 450,
          top: 220,
          width: 550,
          fontSize: 28,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'Creative Director',
          selectable: true,
        },
        {
          type: 'rect',
          left: 450,
          top: 280,
          width: 150,
          height: 3,
          fill: '#E63946',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 450,
          top: 330,
          width: 550,
          fontSize: 20,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'john@example.com\n+1 (555) 123-4567\nwww.example.com',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Business Card - Creative Bold',
    description: 'Bold and creative business card with vibrant colors',
    category: 'business-card',
    widthPx: 1050,
    heightPx: 600,
    tags: ['business', 'creative', 'bold'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1050,
          height: 300,
          fill: '#E63946',
          selectable: true,
        },
        {
          type: 'rect',
          left: 0,
          top: 300,
          width: 1050,
          height: 300,
          fill: '#1A1A1A',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 80,
          width: 890,
          fontSize: 64,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'JANE SMITH',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 170,
          width: 890,
          fontSize: 32,
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'Brand Strategist',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 360,
          width: 890,
          fontSize: 24,
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'jane.smith@company.com\n+1 (555) 987-6543\nwww.janesmith.com',
          selectable: true,
        },
      ],
    },
  },

  // Flyer Templates
  {
    name: 'Event Flyer - Modern Conference',
    description: 'Professional event flyer for conferences',
    category: 'flyer',
    widthPx: 816,
    heightPx: 1056,
    tags: ['event', 'conference', 'professional'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 816,
          height: 1056,
          fill: '#FFFFFF',
          selectable: true,
        },
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 816,
          height: 400,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 120,
          width: 656,
          fontSize: 72,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'TECH SUMMIT',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 220,
          width: 656,
          fontSize: 32,
          fontFamily: 'Inter',
          fill: '#E0E7FF',
          text: '2024',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 480,
          width: 656,
          fontSize: 40,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#1A1A1A',
          text: 'Join us for the biggest tech event of the year',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 650,
          width: 656,
          fontSize: 28,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'March 15-17, 2024\nConvention Center\nNew York, NY',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'rect',
          left: 258,
          top: 850,
          width: 300,
          height: 80,
          fill: '#E63946',
          rx: 12,
          ry: 12,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 278,
          top: 875,
          width: 260,
          fontSize: 32,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'REGISTER NOW',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
];

async function seedTemplates() {
  console.log('🌱 Seeding templates...');

  for (const template of templates) {
    const existing = await prisma.template.findFirst({
      where: { name: template.name },
    });

    if (existing) {
      console.log(`⏭️  Template already exists: ${template.name}`);
      continue;
    }

    await prisma.template.create({
      data: template,
    });
    console.log(`✅ Created template: ${template.name}`);
  }

  console.log('✨ Template seeding complete!');
}

seedTemplates()
  .catch((e) => {
    console.error('❌ Error seeding templates:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
