import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const templates = [
  // Social Media Templates
  {
    name: 'Instagram Post - Bold Typography',
    description: 'Modern Instagram post template with bold text and vibrant colors',
    category: 'social-media',
    widthPx: 1080,
    heightPx: 1080,
    tags: ['instagram', 'social', 'modern', 'bold'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1080,
          height: 1080,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'rect',
          left: 100,
          top: 100,
          width: 880,
          height: 300,
          fill: '#FFFFFF',
          rx: 20,
          ry: 20,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 150,
          top: 180,
          width: 780,
          fontSize: 72,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#2B5FD9',
          text: 'YOUR TITLE HERE',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 150,
          top: 550,
          width: 780,
          fontSize: 36,
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'Add your message or call to action',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Instagram Post - Minimal Quote',
    description: 'Clean and minimal quote template for Instagram',
    category: 'social-media',
    widthPx: 1080,
    heightPx: 1080,
    tags: ['instagram', 'quote', 'minimal', 'clean'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1080,
          height: 1080,
          fill: '#F8F9FA',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 140,
          top: 350,
          width: 800,
          fontSize: 56,
          fontFamily: 'Inter',
          fontStyle: 'italic',
          fill: '#1A1A1A',
          text: '"Your inspiring quote goes here"',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'rect',
          left: 440,
          top: 550,
          width: 200,
          height: 4,
          fill: '#E63946',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 340,
          top: 580,
          width: 400,
          fontSize: 28,
          fontFamily: 'Inter',
          fill: '#666666',
          text: '— Author Name',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Instagram Story - Sale Announcement',
    description: 'Eye-catching Instagram story for sales and promotions',
    category: 'social-media',
    widthPx: 1080,
    heightPx: 1920,
    tags: ['instagram', 'story', 'sale', 'promotion'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1080,
          height: 1920,
          fill: '#E63946',
          selectable: true,
        },
        {
          type: 'circle',
          left: 440,
          top: 300,
          radius: 150,
          fill: '#FFFFFF',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 190,
          top: 700,
          width: 700,
          fontSize: 96,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: '50% OFF',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 140,
          top: 850,
          width: 800,
          fontSize: 48,
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'EVERYTHING',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'rect',
          left: 340,
          top: 1400,
          width: 400,
          height: 100,
          fill: '#1A1A1A',
          rx: 50,
          ry: 50,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 380,
          top: 1430,
          width: 320,
          fontSize: 40,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'SHOP NOW',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Facebook Post - Product Showcase',
    description: 'Eye-catching product showcase for Facebook',
    category: 'social-media',
    widthPx: 1200,
    heightPx: 630,
    tags: ['facebook', 'product', 'showcase'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 600,
          height: 630,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'rect',
          left: 600,
          top: 0,
          width: 600,
          height: 630,
          fill: '#FFFFFF',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 650,
          top: 150,
          width: 500,
          fontSize: 54,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#1A1A1A',
          text: 'NEW PRODUCT',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 650,
          top: 240,
          width: 500,
          fontSize: 32,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'Discover our latest innovation',
          selectable: true,
        },
        {
          type: 'rect',
          left: 650,
          top: 380,
          width: 200,
          height: 60,
          fill: '#E63946',
          rx: 8,
          ry: 8,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 680,
          top: 395,
          width: 140,
          fontSize: 24,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'SHOP NOW',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'LinkedIn Post - Professional Achievement',
    description: 'Professional template for LinkedIn announcements',
    category: 'social-media',
    widthPx: 1200,
    heightPx: 627,
    tags: ['linkedin', 'professional', 'achievement'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1200,
          height: 627,
          fill: '#FFFFFF',
          selectable: true,
        },
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1200,
          height: 15,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 100,
          top: 150,
          width: 1000,
          fontSize: 64,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#1A1A1A',
          text: 'EXCITING NEWS!',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 100,
          top: 280,
          width: 1000,
          fontSize: 36,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'Share your professional milestone',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Pinterest Pin - Recipe',
    description: 'Tall Pinterest pin template perfect for recipes',
    category: 'social-media',
    widthPx: 1000,
    heightPx: 1500,
    tags: ['pinterest', 'recipe', 'food'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1000,
          height: 1500,
          fill: '#FFF8E7',
          selectable: true,
        },
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1000,
          height: 600,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 100,
          top: 700,
          width: 800,
          fontSize: 72,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#1A1A1A',
          text: 'Recipe Name',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 100,
          top: 850,
          width: 800,
          fontSize: 32,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'Quick & Delicious\n⏱ 30 Minutes',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'TikTok Video Cover',
    description: 'Attention-grabbing TikTok video cover template',
    category: 'social-media',
    widthPx: 1080,
    heightPx: 1920,
    tags: ['tiktok', 'video', 'cover'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1080,
          height: 1920,
          fill: '#000000',
          selectable: true,
        },
        {
          type: 'rect',
          left: 0,
          top: 700,
          width: 1080,
          height: 520,
          fill: 'rgba(43, 95, 217, 0.9)',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 140,
          top: 850,
          width: 800,
          fontSize: 80,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'WATCH THIS',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 140,
          top: 1000,
          width: 800,
          fontSize: 48,
          fontFamily: 'Inter',
          fill: '#FFEB3B',
          text: 'You won\'t believe what happens',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Twitter Header - Personal Brand',
    description: 'Professional Twitter header for personal branding',
    category: 'social-media',
    widthPx: 1500,
    heightPx: 500,
    tags: ['twitter', 'header', 'personal'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1500,
          height: 500,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 100,
          top: 150,
          width: 700,
          fontSize: 72,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'YOUR NAME',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 100,
          top: 250,
          width: 700,
          fontSize: 36,
          fontFamily: 'Inter',
          fill: '#E0E7FF',
          text: 'Your tagline or expertise',
          selectable: true,
        },
      ],
    },
  },

  // Banner Templates
  {
    name: 'Web Banner - Announcement',
    description: 'Eye-catching banner for website announcements',
    category: 'banner',
    widthPx: 1200,
    heightPx: 300,
    tags: ['web', 'banner', 'announcement'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1200,
          height: 300,
          fill: '#1A1A1A',
          selectable: true,
        },
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 10,
          height: 300,
          fill: '#E63946',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 50,
          top: 80,
          width: 700,
          fontSize: 56,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'BIG ANNOUNCEMENT',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 50,
          top: 160,
          width: 700,
          fontSize: 28,
          fontFamily: 'Inter',
          fill: '#CCCCCC',
          text: 'Something exciting is coming soon',
          selectable: true,
        },
        {
          type: 'rect',
          left: 900,
          top: 100,
          width: 250,
          height: 100,
          fill: '#2B5FD9',
          rx: 12,
          ry: 12,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 930,
          top: 130,
          width: 190,
          fontSize: 32,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'LEARN MORE',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'YouTube Thumbnail - Tutorial',
    description: 'Attention-grabbing YouTube thumbnail for tutorials',
    category: 'banner',
    widthPx: 1280,
    heightPx: 720,
    tags: ['youtube', 'thumbnail', 'tutorial'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1280,
          height: 720,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'rect',
          left: 40,
          top: 40,
          width: 1200,
          height: 640,
          fill: 'transparent',
          stroke: '#FFFFFF',
          strokeWidth: 8,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 100,
          top: 200,
          width: 1080,
          fontSize: 96,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'HOW TO',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 100,
          top: 350,
          width: 1080,
          fontSize: 64,
          fontFamily: 'Inter',
          fill: '#FFEB3B',
          text: 'Your Tutorial Topic',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'rect',
          left: 480,
          top: 500,
          width: 320,
          height: 120,
          fill: '#E63946',
          rx: 60,
          ry: 60,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 520,
          top: 530,
          width: 240,
          fontSize: 48,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'WATCH',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Email Header - Newsletter',
    description: 'Professional email header for newsletters',
    category: 'banner',
    widthPx: 600,
    heightPx: 200,
    tags: ['email', 'newsletter', 'header'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 600,
          height: 200,
          fill: '#F8F9FA',
          selectable: true,
        },
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 600,
          height: 8,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 50,
          top: 70,
          width: 500,
          fontSize: 48,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#1A1A1A',
          text: 'Your Newsletter',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },

  // Business Card Templates
  {
    name: 'Business Card - Modern Professional',
    description: 'Clean and modern business card design',
    category: 'business-card',
    widthPx: 1050,
    heightPx: 600,
    tags: ['business', 'professional', 'modern'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1050,
          height: 600,
          fill: '#FFFFFF',
          selectable: true,
        },
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 400,
          height: 600,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 450,
          top: 150,
          width: 550,
          fontSize: 48,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#1A1A1A',
          text: 'John Doe',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 450,
          top: 220,
          width: 550,
          fontSize: 28,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'Creative Director',
          selectable: true,
        },
        {
          type: 'rect',
          left: 450,
          top: 280,
          width: 150,
          height: 3,
          fill: '#E63946',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 450,
          top: 330,
          width: 550,
          fontSize: 20,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'john@example.com\n+1 (555) 123-4567\nwww.example.com',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Business Card - Creative Bold',
    description: 'Bold and creative business card with vibrant colors',
    category: 'business-card',
    widthPx: 1050,
    heightPx: 600,
    tags: ['business', 'creative', 'bold'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1050,
          height: 300,
          fill: '#E63946',
          selectable: true,
        },
        {
          type: 'rect',
          left: 0,
          top: 300,
          width: 1050,
          height: 300,
          fill: '#1A1A1A',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 80,
          width: 890,
          fontSize: 64,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'JANE SMITH',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 170,
          width: 890,
          fontSize: 32,
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'Brand Strategist',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 360,
          width: 890,
          fontSize: 24,
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'jane.smith@company.com\n+1 (555) 987-6543\nwww.janesmith.com',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Business Card - Minimalist',
    description: 'Ultra-minimal business card with clean typography',
    category: 'business-card',
    widthPx: 1050,
    heightPx: 600,
    tags: ['business', 'minimal', 'clean'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1050,
          height: 600,
          fill: '#1A1A1A',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 200,
          width: 890,
          fontSize: 56,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'Alex Johnson',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 280,
          width: 890,
          fontSize: 24,
          fontFamily: 'Inter',
          fill: '#CCCCCC',
          text: 'Designer • Developer • Creator',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 400,
          width: 890,
          fontSize: 20,
          fontFamily: 'Inter',
          fill: '#999999',
          text: 'hello@alexjohnson.com',
          selectable: true,
        },
      ],
    },
  },

  // Flyer Templates
  {
    name: 'Event Flyer - Modern Conference',
    description: 'Professional event flyer for conferences',
    category: 'flyer',
    widthPx: 816,
    heightPx: 1056,
    tags: ['event', 'conference', 'professional'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 816,
          height: 1056,
          fill: '#FFFFFF',
          selectable: true,
        },
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 816,
          height: 400,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 120,
          width: 656,
          fontSize: 72,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'TECH SUMMIT',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 220,
          width: 656,
          fontSize: 32,
          fontFamily: 'Inter',
          fill: '#E0E7FF',
          text: '2024',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 480,
          width: 656,
          fontSize: 40,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#1A1A1A',
          text: 'Join us for the biggest tech event of the year',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 650,
          width: 656,
          fontSize: 28,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'March 15-17, 2024\nConvention Center\nNew York, NY',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'rect',
          left: 258,
          top: 850,
          width: 300,
          height: 80,
          fill: '#E63946',
          rx: 12,
          ry: 12,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 278,
          top: 875,
          width: 260,
          fontSize: 32,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'REGISTER NOW',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Party Flyer - Night Club',
    description: 'Vibrant party flyer for nightlife events',
    category: 'flyer',
    widthPx: 816,
    heightPx: 1056,
    tags: ['party', 'club', 'event'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 816,
          height: 1056,
          fill: '#000000',
          selectable: true,
        },
        {
          type: 'circle',
          left: 258,
          top: 200,
          radius: 150,
          fill: '#E63946',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 450,
          width: 656,
          fontSize: 80,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'SATURDAY',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 560,
          width: 656,
          fontSize: 64,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#E63946',
          text: 'NIGHT',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 700,
          width: 656,
          fontSize: 32,
          fontFamily: 'Inter',
          fill: '#CCCCCC',
          text: 'DECEMBER 25 • 10 PM\nDOWNTOWN CLUB',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Sale Flyer - Retail',
    description: 'Eye-catching sale flyer for retail stores',
    category: 'flyer',
    widthPx: 816,
    heightPx: 1056,
    tags: ['sale', 'retail', 'shopping'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 816,
          height: 1056,
          fill: '#FFEB3B',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 200,
          width: 656,
          fontSize: 120,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#1A1A1A',
          text: 'MEGA',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 330,
          width: 656,
          fontSize: 120,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#E63946',
          text: 'SALE',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'rect',
          left: 158,
          top: 550,
          width: 500,
          height: 120,
          fill: '#1A1A1A',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 178,
          top: 580,
          width: 460,
          fontSize: 56,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'UP TO 70% OFF',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 750,
          width: 656,
          fontSize: 28,
          fontFamily: 'Inter',
          fill: '#1A1A1A',
          text: 'Limited Time Only!\nVisit us this weekend',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },

  // Poster Templates
  {
    name: 'Motivational Poster - Dream Big',
    description: 'Inspiring motivational poster',
    category: 'poster',
    widthPx: 1080,
    heightPx: 1350,
    tags: ['motivational', 'inspiration', 'quote'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1080,
          height: 1350,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 140,
          top: 450,
          width: 800,
          fontSize: 96,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'DREAM',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 140,
          top: 600,
          width: 800,
          fontSize: 96,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFEB3B',
          text: 'BIG',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 140,
          top: 800,
          width: 800,
          fontSize: 36,
          fontFamily: 'Inter',
          fill: '#E0E7FF',
          text: 'Work hard and make it happen',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Movie Poster - Action',
    description: 'Dramatic action movie poster template',
    category: 'poster',
    widthPx: 900,
    heightPx: 1350,
    tags: ['movie', 'cinema', 'action'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 900,
          height: 1350,
          fill: '#1A1A1A',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 900,
          width: 740,
          fontSize: 100,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'MOVIE TITLE',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 1050,
          width: 740,
          fontSize: 32,
          fontFamily: 'Inter',
          fill: '#CCCCCC',
          text: 'COMING SOON',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'rect',
          left: 350,
          top: 1150,
          width: 200,
          height: 6,
          fill: '#E63946',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Concert Poster - Live Music',
    description: 'Energetic concert poster design',
    category: 'poster',
    widthPx: 1080,
    heightPx: 1350,
    tags: ['concert', 'music', 'event'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1080,
          height: 1350,
          fill: '#E63946',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 140,
          top: 250,
          width: 800,
          fontSize: 48,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'LIVE IN CONCERT',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 140,
          top: 450,
          width: 800,
          fontSize: 120,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'ARTIST',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 140,
          top: 620,
          width: 800,
          fontSize: 120,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFEB3B',
          text: 'NAME',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'rect',
          left: 290,
          top: 950,
          width: 500,
          height: 100,
          fill: '#1A1A1A',
          rx: 12,
          ry: 12,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 310,
          top: 980,
          width: 460,
          fontSize: 40,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'GET TICKETS',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },

  // Invitation Templates
  {
    name: 'Wedding Invitation - Elegant',
    description: 'Elegant wedding invitation template',
    category: 'invitation',
    widthPx: 900,
    heightPx: 1200,
    tags: ['wedding', 'elegant', 'formal'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 900,
          height: 1200,
          fill: '#F8F9FA',
          selectable: true,
        },
        {
          type: 'rect',
          left: 50,
          top: 50,
          width: 800,
          height: 1100,
          fill: 'transparent',
          stroke: '#2B5FD9',
          strokeWidth: 3,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 150,
          top: 250,
          width: 600,
          fontSize: 32,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'You are invited to the wedding of',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 150,
          top: 400,
          width: 600,
          fontSize: 72,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#2B5FD9',
          text: 'Bride & Groom',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'rect',
          left: 350,
          top: 520,
          width: 200,
          height: 3,
          fill: '#E63946',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 150,
          top: 650,
          width: 600,
          fontSize: 28,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'Saturday, June 15, 2024\n4:00 PM\nVenue Name',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Birthday Invitation - Fun',
    description: 'Fun and colorful birthday invitation',
    category: 'invitation',
    widthPx: 900,
    heightPx: 1200,
    tags: ['birthday', 'party', 'celebration'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 900,
          height: 1200,
          fill: '#FFEB3B',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 150,
          top: 200,
          width: 600,
          fontSize: 96,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#E63946',
          text: 'PARTY!',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 150,
          top: 350,
          width: 600,
          fontSize: 48,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#1A1A1A',
          text: 'Join us for',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 150,
          top: 450,
          width: 600,
          fontSize: 64,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#2B5FD9',
          text: 'Name\'s Birthday',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'rect',
          left: 200,
          top: 700,
          width: 500,
          height: 200,
          fill: '#FFFFFF',
          rx: 20,
          ry: 20,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 220,
          top: 750,
          width: 460,
          fontSize: 32,
          fontFamily: 'Inter',
          fill: '#1A1A1A',
          text: 'Saturday, 3 PM\nVenue Address',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Baby Shower Invitation',
    description: 'Sweet baby shower invitation template',
    category: 'invitation',
    widthPx: 900,
    heightPx: 1200,
    tags: ['baby', 'shower', 'celebration'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 900,
          height: 1200,
          fill: '#E0E7FF',
          selectable: true,
        },
        {
          type: 'circle',
          left: 350,
          top: 150,
          radius: 100,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 150,
          top: 400,
          width: 600,
          fontSize: 48,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'You\'re Invited to a',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 150,
          top: 500,
          width: 600,
          fontSize: 72,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#2B5FD9',
          text: 'Baby Shower',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 150,
          top: 700,
          width: 600,
          fontSize: 32,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'Celebrating\nMom-to-be\'s Name',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },

  // Certificate Templates
  {
    name: 'Certificate of Achievement',
    description: 'Professional achievement certificate',
    category: 'certificate',
    widthPx: 1400,
    heightPx: 1000,
    tags: ['certificate', 'achievement', 'award'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1400,
          height: 1000,
          fill: '#FFFFFF',
          selectable: true,
        },
        {
          type: 'rect',
          left: 40,
          top: 40,
          width: 1320,
          height: 920,
          fill: 'transparent',
          stroke: '#2B5FD9',
          strokeWidth: 8,
          selectable: true,
        },
        {
          type: 'rect',
          left: 60,
          top: 60,
          width: 1280,
          height: 880,
          fill: 'transparent',
          stroke: '#E63946',
          strokeWidth: 2,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 200,
          top: 150,
          width: 1000,
          fontSize: 80,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#2B5FD9',
          text: 'CERTIFICATE',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 200,
          top: 250,
          width: 1000,
          fontSize: 40,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'OF ACHIEVEMENT',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 200,
          top: 400,
          width: 1000,
          fontSize: 28,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'This certificate is proudly presented to',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 200,
          top: 500,
          width: 1000,
          fontSize: 64,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#1A1A1A',
          text: 'Recipient Name',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'rect',
          left: 500,
          top: 610,
          width: 400,
          height: 3,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 200,
          top: 700,
          width: 1000,
          fontSize: 24,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'For outstanding performance and dedication',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Certificate of Completion',
    description: 'Course completion certificate',
    category: 'certificate',
    widthPx: 1400,
    heightPx: 1000,
    tags: ['certificate', 'completion', 'training'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1400,
          height: 1000,
          fill: '#F8F9FA',
          selectable: true,
        },
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1400,
          height: 200,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 200,
          top: 50,
          width: 1000,
          fontSize: 72,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'CERTIFICATE OF COMPLETION',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 200,
          top: 350,
          width: 1000,
          fontSize: 32,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'This is to certify that',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 200,
          top: 450,
          width: 1000,
          fontSize: 56,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#2B5FD9',
          text: 'Student Name',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 200,
          top: 600,
          width: 1000,
          fontSize: 28,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'has successfully completed',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 200,
          top: 680,
          width: 1000,
          fontSize: 40,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#1A1A1A',
          text: 'Course Title',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },

  // Presentation Templates
  {
    name: 'Presentation Slide - Title',
    description: 'Modern presentation title slide',
    category: 'presentation',
    widthPx: 1920,
    heightPx: 1080,
    tags: ['presentation', 'title', 'slide'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1920,
          height: 1080,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 200,
          top: 350,
          width: 1520,
          fontSize: 120,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'Presentation Title',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 200,
          top: 550,
          width: 1520,
          fontSize: 48,
          fontFamily: 'Inter',
          fill: '#E0E7FF',
          text: 'Your Name • Date',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'rect',
          left: 760,
          top: 700,
          width: 400,
          height: 6,
          fill: '#E63946',
          selectable: true,
        },
      ],
    },
  },
  {
    name: 'Presentation Slide - Content',
    description: 'Clean content slide for presentations',
    category: 'presentation',
    widthPx: 1920,
    heightPx: 1080,
    tags: ['presentation', 'content', 'slide'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1920,
          height: 1080,
          fill: '#FFFFFF',
          selectable: true,
        },
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1920,
          height: 15,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 150,
          top: 100,
          width: 1620,
          fontSize: 72,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#2B5FD9',
          text: 'Slide Title',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 150,
          top: 250,
          width: 1620,
          fontSize: 36,
          fontFamily: 'Inter',
          fill: '#666666',
          text: '• Key point one\n• Key point two\n• Key point three',
          selectable: true,
        },
      ],
    },
  },

  // Menu Templates
  {
    name: 'Restaurant Menu - Modern',
    description: 'Sleek modern restaurant menu',
    category: 'menu',
    widthPx: 900,
    heightPx: 1200,
    tags: ['restaurant', 'menu', 'food'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 900,
          height: 1200,
          fill: '#1A1A1A',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 100,
          top: 100,
          width: 700,
          fontSize: 80,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'MENU',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'rect',
          left: 350,
          top: 200,
          width: 200,
          height: 4,
          fill: '#E63946',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 100,
          top: 300,
          width: 700,
          fontSize: 48,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#E63946',
          text: 'STARTERS',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 100,
          top: 400,
          width: 700,
          fontSize: 28,
          fontFamily: 'Inter',
          fill: '#CCCCCC',
          text: 'Appetizer Name ......... $12\nAppetizer Name ......... $15',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 100,
          top: 600,
          width: 700,
          fontSize: 48,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#E63946',
          text: 'MAIN COURSES',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 100,
          top: 700,
          width: 700,
          fontSize: 28,
          fontFamily: 'Inter',
          fill: '#CCCCCC',
          text: 'Main Dish Name ......... $24\nMain Dish Name ......... $28',
          selectable: true,
        },
      ],
    },
  },

  // Resume Templates
  {
    name: 'Resume - Professional',
    description: 'Clean professional resume template',
    category: 'resume',
    widthPx: 816,
    heightPx: 1056,
    tags: ['resume', 'cv', 'professional'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 816,
          height: 1056,
          fill: '#FFFFFF',
          selectable: true,
        },
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 300,
          height: 1056,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 350,
          top: 80,
          width: 420,
          fontSize: 56,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#1A1A1A',
          text: 'Your Name',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 350,
          top: 160,
          width: 420,
          fontSize: 24,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'Professional Title',
          selectable: true,
        },
        {
          type: 'rect',
          left: 350,
          top: 220,
          width: 150,
          height: 3,
          fill: '#E63946',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 40,
          top: 100,
          width: 220,
          fontSize: 32,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'CONTACT',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 40,
          top: 180,
          width: 220,
          fontSize: 18,
          fontFamily: 'Inter',
          fill: '#E0E7FF',
          text: 'email@example.com\n+1 (555) 123-4567\nCity, Country',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 350,
          top: 300,
          width: 420,
          fontSize: 32,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#2B5FD9',
          text: 'EXPERIENCE',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 350,
          top: 370,
          width: 420,
          fontSize: 20,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'Job Title\nCompany Name • 2020-2024',
          selectable: true,
        },
      ],
    },
  },

  // Logo Design Templates
  {
    name: 'Logo - Circular Badge',
    description: 'Circular badge logo template',
    category: 'logo',
    widthPx: 800,
    heightPx: 800,
    tags: ['logo', 'badge', 'circular'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 800,
          height: 800,
          fill: '#FFFFFF',
          selectable: true,
        },
        {
          type: 'circle',
          left: 300,
          top: 300,
          radius: 200,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'circle',
          left: 330,
          top: 330,
          radius: 140,
          fill: 'transparent',
          stroke: '#FFFFFF',
          strokeWidth: 6,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 250,
          top: 350,
          width: 300,
          fontSize: 48,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'LOGO',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },

  // Infographic Templates
  {
    name: 'Infographic - Stats',
    description: 'Data visualization infographic',
    category: 'infographic',
    widthPx: 1080,
    heightPx: 1920,
    tags: ['infographic', 'data', 'stats'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1080,
          height: 1920,
          fill: '#F8F9FA',
          selectable: true,
        },
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1080,
          height: 300,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 140,
          top: 80,
          width: 800,
          fontSize: 72,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'KEY STATISTICS',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'rect',
          left: 140,
          top: 450,
          width: 800,
          height: 300,
          fill: '#FFFFFF',
          rx: 20,
          ry: 20,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 190,
          top: 520,
          width: 700,
          fontSize: 96,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#E63946',
          text: '87%',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 190,
          top: 650,
          width: 700,
          fontSize: 32,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'Your Statistic Description',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'rect',
          left: 140,
          top: 900,
          width: 800,
          height: 300,
          fill: '#FFFFFF',
          rx: 20,
          ry: 20,
          selectable: true,
        },
        {
          type: 'textbox',
          left: 190,
          top: 970,
          width: 700,
          fontSize: 96,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#2B5FD9',
          text: '2.5M',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 190,
          top: 1100,
          width: 700,
          fontSize: 32,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'Another Important Metric',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },

  // Email Signature Template
  {
    name: 'Email Signature - Professional',
    description: 'Clean email signature template',
    category: 'email',
    widthPx: 600,
    heightPx: 200,
    tags: ['email', 'signature', 'professional'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 600,
          height: 200,
          fill: '#FFFFFF',
          selectable: true,
        },
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 5,
          height: 200,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 30,
          top: 40,
          width: 550,
          fontSize: 28,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#1A1A1A',
          text: 'Your Name',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 30,
          top: 80,
          width: 550,
          fontSize: 18,
          fontFamily: 'Inter',
          fill: '#666666',
          text: 'Job Title • Company Name',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 30,
          top: 120,
          width: 550,
          fontSize: 16,
          fontFamily: 'Inter',
          fill: '#2B5FD9',
          text: 'email@company.com • +1 (555) 123-4567',
          selectable: true,
        },
      ],
    },
  },

  // Coupon Template
  {
    name: 'Coupon - Discount',
    description: 'Promotional coupon design',
    category: 'coupon',
    widthPx: 1000,
    heightPx: 400,
    tags: ['coupon', 'discount', 'promotion'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1000,
          height: 400,
          fill: '#E63946',
          selectable: true,
        },
        {
          type: 'rect',
          left: 40,
          top: 40,
          width: 920,
          height: 320,
          fill: 'transparent',
          stroke: '#FFFFFF',
          strokeWidth: 3,
          strokeDashArray: [10, 5],
          selectable: true,
        },
        {
          type: 'textbox',
          left: 100,
          top: 100,
          width: 800,
          fontSize: 80,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: '25% OFF',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 100,
          top: 220,
          width: 800,
          fontSize: 32,
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'Use code: SAVE25',
          textAlign: 'center',
          selectable: true,
        },
      ],
    },
  },

  // Bookmark Template
  {
    name: 'Bookmark - Motivational',
    description: 'Inspirational bookmark design',
    category: 'bookmark',
    widthPx: 600,
    heightPx: 1800,
    tags: ['bookmark', 'reading', 'motivation'],
    data: {
      version: '5.3.0',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 600,
          height: 1800,
          fill: '#2B5FD9',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 700,
          width: 440,
          fontSize: 56,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          fill: '#FFFFFF',
          text: 'READ MORE',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'textbox',
          left: 80,
          top: 850,
          width: 440,
          fontSize: 32,
          fontFamily: 'Inter',
          fill: '#E0E7FF',
          text: 'Knowledge is power',
          textAlign: 'center',
          selectable: true,
        },
        {
          type: 'rect',
          left: 200,
          top: 1000,
          width: 200,
          height: 4,
          fill: '#E63946',
          selectable: true,
        },
      ],
    },
  },
];

async function seedTemplates() {
  console.log('🌱 Seeding templates...');

  for (const template of templates) {
    const existing = await prisma.template.findFirst({
      where: { name: template.name },
    });

    if (existing) {
      console.log(`⏭️  Template already exists: ${template.name}`);
      continue;
    }

    await prisma.template.create({
      data: template,
    });
    console.log(`✅ Created template: ${template.name}`);
  }

  console.log('✨ Template seeding complete!');
}

seedTemplates()
  .catch((e) => {
    console.error('❌ Error seeding templates:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
